version: '3.8'

services:
  psql:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      - POSTGRES_DB=learning_platform_db
      - POSTGRES_USER=postgre_user
      - POSTGRES_PASSWORD=postgre_password
    volumes:
      - database-data:/var/lib/postgresql


volumes:
  database-data: